language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: lit-dawn-26947
  api_key:
    secure: b5sISVUtGlxF3pm/QRzSLV/ecEROwU2KBs9zK+/QJ9ZDwtK2rOC0Jc8019r9QGr2vYd5yS7zRKFeOoRVsCuI7hXKkZATmVOpCQgxDhMR76xppmax828fmVS8KEJqnteGi64EGO9Lq3AZRf450Au7UyUYTDw0UzdI4BS5kf7erqVXUurv2xKjov4q0To4xPltzJ+4r5h7M7FXQKVEzHZ2hJDKX6mgF4zph9hMKp5hvEL6Ibqn52yl/XmpQyJb7xyspIR2N7dUXtD4eLIrTfjjzJU/47i+5VC84hNYAZWTBScn0DxWQkuRWvqSB6ko4spU5pn4Qu7pB7O9dUawPrawsLuCr7LzIu9lnXiXrth8QZGAInDvlNvFIqKAciTto9LVwOYY4e5qX3oBqy2PRYCMLFb6udb+91ibNxETDAquw5CCwDrqIyxpPclUZKUf62dp9jEJzWYbd8cKjHd8wcz9LcrItEqyeBTbT7pOx9aOuNoD/zkq/QTmHm808zNELjdkzRZelX4YGpwXYgfkSU6zVDJ3WjQsAgQLmENqw780AG8k/dgoIAXSbib2AZVp49zglgNQxZHPnLtzuWiz8aLgOxXtzzw+jEpqFfcfXFixAJjrgsOJDa0OQGedOc7wYlkb0Q+E2/qOcDmPC0JzG3WJoow4BpuIoJnpQTmpbgcmZgE=
  app: node-restaurants-app-mongoose
  on:
    repo: jolo217/node-restaurants-app-mongoose
